### ISSUE TITLE
rename Stagefright.java to StageFright.java

### ISSUE THREAD

**Issue by mpeck12** [nowsecure/android-vts#10]
Great work!

One minor issue: I had an error compiling because "Stagefright.java" (app/src/main/java/fuzion24/device/vulnerability/vulnerabilities/framework/media/Stagefright.java) should be "StageFright.java" because the class is named StageFright.

I'd submit a pull request but I'm having trouble getting git to recognize that I changed the file name as it appears to not recognize case changes, maybe you can figure out how to do that. :-)

**Comment by dweinstein** [comment]
guess now you know what platform we build this on ;-)

**Comment by Fuzion24** [comment]
https://github.com/nowsecure/android-vts/commit/93c65a0111148c5cad06eb0542300eb1804e6806
