### ISSUE TITLE
I added VTS to TorrApk

### ISSUE THREAD

**Issue by gianzalone77** [nowsecure/android-vts#102]
Hello,
I'm really disappointed to know that Google suspended the VTS app. I think it's a nice and useful project and I really like it's open-source nature.
I added the VTS app to TorrApk, an alternative free Android app-store I'm working on.
I'll keep VTS app updated by pulling the latest apk file directly from this github.

This is the link to the app on TorrApk, I hope it could be useful:
https://www.torrapk.com/en/apps/22-tools-and-personalization/10371-VTS-for-Android

Every comment or suggestion is welcome.
Thank you,
Giuseppe

**Comment by SecUpwN** [comment]
@nowsecure, please close this Issue, TorrApk is down.

**Comment by gianzalone77** [comment]
@SecUpwN, it's not true, TorrApk is on and it works.

**Comment by SecUpwN** [comment]
>@SecUpwN, it's not true, TorrApk is on and it works. 

Thanks. Seems like it has problems with [Tor](https://www.torproject.org/). Either way, this is solved.

**Comment by qaz1243qaz** [comment]
@gianzalone77 
How to submit APP to TorrApk？
Registration is complete. I can not receive a verification code.
