### ISSUE TITLE
bin/VulnChecker.apk can not be installed normally

### ISSUE THREAD

**Issue by sunnyjiang** [nowsecure/android-vts#13]
W/PackageParser( 3605): Unable to read AndroidManifest.xml of /data/local/tmp/VulnChecker.apk
W/PackageParser( 3605): java.io.FileNotFoundException: AndroidManifest.xml

**Comment by Fuzion24** [comment]
how did you download it? is the the file valid?

**Comment by Fuzion24** [comment]
closing this...

**Comment by sunnyjiang** [comment]
I just downloaded APK from bin/ dir, and use adb install, then get the error msg. Android 4.4

**Comment by Fuzion24** [comment]
what is the sha1 of the file you downloaded?
