### ISSUE TITLE
False positives for WeakSauce and StumpRoot

### ISSUE THREAD

**Issue by CunningLogic** [nowsecure/android-vts#14]
I suggest pulling tests for WeakSauce and StumpRoot until they can be re-written, as both will often cause false positives.

I'm really to rewrite them at some point in the future when time allows.

**Comment by Fuzion24** [comment]
@CunningLogic https://github.com/nowsecure/android-vts/commit/44be526e8ef6e92c34469a5a7c784661d64e6414  I pulled them the other day. Looking forward to your pull req :-D
