### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by trufae** [nowsecure/android-vts#42]
When starting the app, show a bigger search button in the middle of the screen. Right under the "Start the scan to get the results" message.

Improvement. When tapping it, make an animation to shrink it and move it to the lower-right corner of the screen where it's placed right now.

**Comment by Fuzion24** [comment]
@SandroMachado What do you think about this suggestion?

**Comment by SandroMachado** [comment]
The suggestion is great but to do that kind of animations take a lot of time. To increase the difficulty, the FAB button is attached to the recycler view to hide/animate with the scroll... So it is not just increase the size and move to bottom/right... :(

IMO, this should be kept in mind but should not be a priority, there are a lot of improvements that can be made before this one.

**Comment by giantpune** [comment]
I think the magnifying glass icon is not clear.  Most people associate that with a search function, not with "make the app work" or "scan".

**Comment by radare** [comment]
Agree, maybe use the play button?

**Comment by SandroMachado** [comment]
The action is *scan*. I can find, searching on [Icon Finder](https://www.iconfinder.com/search/?q=scan) some magnifying glass icons for the keyword `scan`. But, I can confess, that the first icon I used to the FAB button was a *play*, but in the end I decided to for the magnifying glass icon. :)

**Comment by ctz** [comment]
personally i would make the scan start when opening the app, and make the results rows contain spinners while the tests are running. just my 2c.

**Comment by indrora** [comment]
I'll leave this here, since I found this ticket: [Radar](https://materialdesignicons.com/icon/radar) is a perfectly acceptable solution for replacing the "scan" button. Alternatively, combining the [Bug](https://materialdesignicons.com/icon/bug) and part of the ["account search"](https://materialdesignicons.com/icon/account-search) graphics would work fine enough.

I can mash up some imagery if need be. Potentially, bug + radar would be a good idea.

**Comment by indrora** [comment]
One combination of bug + search glass

![bug-find-24](https://cloud.githubusercontent.com/assets/470584/11163256/672e06b8-8a85-11e5-870e-35b9123f031b.png) ![bug-find-48](https://cloud.githubusercontent.com/assets/470584/11163254/672cab74-8a85-11e5-911b-7e1df5789290.png) ![bug-find-128](https://cloud.githubusercontent.com/assets/470584/11163258/672e5a3c-8a85-11e5-9b1d-45c3aae922f6.png)

Another combination of bug + search

![bug-search-24](https://cloud.githubusercontent.com/assets/470584/11163282/0d6fadec-8a86-11e5-87b9-7c29e8719e47.png) ![bug-search-48](https://cloud.githubusercontent.com/assets/470584/11163281/0d6f7d54-8a86-11e5-9ba3-302855f76ec9.png) ![bug-search-128](https://cloud.githubusercontent.com/assets/470584/11163283/0d70d3f2-8a86-11e5-8d68-a3462df82c50.png)


And a combination of bug + radar

![bug-radar-24](https://cloud.githubusercontent.com/assets/470584/11163259/6731c000-8a85-11e5-8c3d-630af5f8336d.png) ![bug-radar-48](https://cloud.githubusercontent.com/assets/470584/11163255/672d392c-8a85-11e5-82df-03974acbc00d.png) ![bug-radar-128](https://cloud.githubusercontent.com/assets/470584/11163257/672e02ee-8a85-11e5-9ddb-2aeb6e0cc863.png)

**Comment by SandroMachado** [comment]
@indrora I really like the combination of the bug + radar. The icon should be white to be added to the FAB button...Don't you want to make a PR with this icon? It is just replace the all the icons with the name `ic_action_start.png`.

**Comment by indrora** [comment]
My problem with bug + radar is that it looks nasty at maller resolutions. The first image in that set is 24px, which is what you'll see on actual devices.

**Comment by radare** [comment]
What about a button with SCAN text in it?

**Comment by SandroMachado** [comment]
The FAB buttons should only have an icon. More info here: https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions

**Comment by dweinstein** [comment]
what about the assessment icon

**Comment by SandroMachado** [comment]
@deanlandolt like this:

![device-2015-11-15-230208](https://cloud.githubusercontent.com/assets/631739/11171654/111bbc5c-8bed-11e5-98f5-043925714654.png)

**Comment by Fuzion24** [comment]
Can we move the scan button to the center middle until after the first scan runs? so that it's right under and centered underneath .. "Start the scan to get the results"?

**Comment by dweinstein** [comment]
:+1: I like this assessment button

**Comment by SandroMachado** [comment]
@Fuzion24 I am used to see the FAB buttons at the bottom/Right corner... Even in the empty views. Probably just replace by the assessment icon and maybe change the message to "Press the button to start the vulnerabilities scan. Once they finish you will see them here."

![nexus2cee_screenshot_2014-10-19-09-13-00](https://cloud.githubusercontent.com/assets/631739/11227787/2847bd92-8d80-11e5-84c2-cad86dac841e.png)

**Comment by Fuzion24** [comment]
works for me...
