### ISSUE TITLE
Failed test: yellow isn't very readable

### ISSUE THREAD

**Issue by Shadorc** [nowsecure/android-vts#57]
Hi !

Thanks for the new update, it's nice to have some information about the issues.
But the new yellow color for failed test isn't very readable, maybe orange ?

![Screenshot](http://i.imgur.com/7j7iba5.png)

**Comment by Fuzion24** [comment]
@Shadorc  Thanks for the issue: would you mind trying this binary (where yellow is swapped for orange) and taking a screenshot: https://github.com/nowsecure/android-vts/raw/bins/bin/androidVTS.apk

**Comment by Shadorc** [comment]
It's not orange...
But it's readable !
![Screenshot](http://i.imgur.com/0wEIjb9.png)

**Comment by Fuzion24** [comment]
Fixed -- will be included in the next release. Thanks.

**Comment by dweinstein** [comment]
fixed in 095e784ab1a467c3952b5711b3bb217d5ebe3e4d

**Comment by eonnes** [comment]
I  have the yellow problem in the most recent version of the app. Is it back or a mistake?

**Comment by eonnes** [comment]
I got version v.6
I did get the program into the Netherlands by play store.

**Comment by Fuzion24** [comment]
v.9 should propagate to the play store shortly.. just hang tight.

**Comment by eonnes** [comment]
Problem solved. I got now the version v.9
Thanks.
