### ISSUE TITLE
make output easily shareable

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/android-vts#6]
- json on logcat and ask for gist?
- allow opt-in to share results back to us for research purposes?
- button to copy results to clipboard?

**Comment by ctz** [comment]
I've had good results in a [similar tool](https://github.com/ctz/tee-checker) by just starting a VIEW intent to a Google Forms submit URL. Requires the minimum amount of code, and you get a (public or private) spreadsheet of results out the end.

**Comment by trufae** [comment]
Sharing by mail can be useful too

**Comment by dweinstein** [comment]
:+1: I think the approach that @ctz shared could be easily used to do that as well. if I find some spare time this week I'll take a stab at implementing the suggestions

**Comment by Fuzion24** [comment]
@dweinstein should we close this one?
