### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by ctz** [nowsecure/android-vts#7]
My apologies if I missed it, but I can't seem to find the license this code is released under. It'd be great if there was an explicit license file :)

**Comment by strazzere** [comment]
+2 No license is listed. My assumption is this means it's the most strict license possible, can we get a confirmation/fix ?

**Comment by teull** [comment]
@ctz @strazzere thanks for inquiring. We've added the MIT license and copyright statement. Appreciate the interest and hope folks can benefit and contribute.

**Comment by dweinstein** [comment]
:+1:
