### ISSUE TITLE
Intro-Slides / questions on first install

### ISSUE THREAD

**Issue by Fuzion24** [nowsecure/android-vts#89]
On first run, a dialog stating that some A/V may (incorrectly) detect this as a virus, make the user explicitly accept this.

This dialog could also ask them to opt-in to data sharing as well.

**Comment by SandroMachado** [comment]
To disable the opt-in I was thinking in adding another entry in the overflow menu with a checkbox with the text `Disable\Enable automatic sharing the scan results`. Like this:

![gwbi7](https://cloud.githubusercontent.com/assets/631739/11519864/78538cec-9895-11e5-8a5a-3e63eceaafc0.png)

Probably in the future it will be necessary to create a preferences screen.

@Fuzion24 WDYT?

**Comment by Fuzion24** [comment]
yea, that works for me.  I think it's pretty important that we do make the user explicitly check this. 

The other thing I wanted to bring up is to somehow convey to the user that overall secureness of the device is not static and this only represents a snapshot in time.

**Comment by Fuzion24** [comment]
I guess to clarify what i was thinking:
We could force users to read a couple of intro slides of first install.

Like:
Slide 1)
   Convey the security of the device changes overtime
Slide 2)
   Tell the user if the device reboots, or a test hangs, the device is likely vulnerable
Slide 3)
  Explain that Antivirus are dumb
Slide 4)
  Explain the benefit of data sharing and ask them to opt-in (the option to opt out at any time is still a good idea)

**Comment by Fuzion24** [comment]
maybe something like this : https://github.com/PaoloRotolo/AppIntro

**Comment by SandroMachado** [comment]
I totally agree with you.
Do you have any suggestions for the text to be displayed to the user in each slide? 

My suggestion:

- Slide1:
The security of the device changes overtime, make sure you run periodically scans.

- Slide2:
If your device reboots, or a test hangs, the device is likely vulnerable, but our testing cant determine this with certainty.

- Slide3:
Antivirus does not make you more secure, they generally make you much less secure by greatly increasing the attack surface.

- Slide4:
Sharing the tests results will help to increase the knowledge about the android devices that contains security issues. The device information collected does not contains unique identifiers. Nothing related to your Google (or any other) account is collected.

**Comment by Fuzion24** [comment]
I think that's a good start! We can tweak it after the first implementation

**Comment by Fuzion24** [comment]
Fixed by #96
